--ADDING A PRIMARY KEY TO THE TABLE AND CHECKING ITS UNIQEUNESS--
--CREATING A PRIMARY KEY FOR THE DATASET--
ALTER TABLE artist_streaming_info_clean
ADD id INT IDENTITY(1,1) PRIMARY KEY;

--CHECKING UNIQUENESS OF PRIMARY KEY--
SELECT 
id,
count(*) 
FROM artist_streaming_info_clean
GROUP BY id
HAVING COUNT(*)=1 or id IS NULL
